export const en = {
  "navbar.button.home": "HOME",
  "navbar.button.games": "GAMES",
  "navbar.button.projects": "PROJECTS",
  "navbar.button.services": "SERVICES",
  "navbar.button.contacts": "CONTACTS",
  "home.header.title": "Hola! I'm MIRO.👋",
  "home.header.subtitle": "Computer Science Engineering Student & Software Engineer...",
  "home.body.text": "I’m a Computer Science Engineering student at the National School of Computer Science and a part-time Software Engineer at Expensya by Medius. I love using technology to create solutions that make a difference. Game development is my favorite hobby, and I enjoy building fun and immersive experiences. Join me on my journey as I combine my skills in software engineering and game development!",
  "cards.button.text": "READ MORE ->",
  "services.fullstack.title": "Full Stack Development",
  "services.fullstack.bodytext": "I can help you build robust full-stack applications, including both backend and frontend development. With my expertise in full-stack development, I can create solutions tailored to your needs.",
  "services.ai.title": "AI Development",
  "services.ai.bodytext": "I specialize in AI fields such as NLP, OCR, and Computer Vision. Let's leverage the power of AI to build innovative solutions for your business.",
  "services.game.title": "Game Development",
  "services.game.bodytext": "I do game development and design for fun and freelancing. Let's create engaging and immersive gaming experiences together.",
  "services.skills.header": "MY SKILLS",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "GAME ENGINES AND DIVERSE TOOLS",
  "contact.header.title": "Contact Me",
  "contact.github.title": "GitHub:",
  "contact.github.text": "-> My GitHub Profile",
  "contact.leetcode.title": "LeetCode:",
  "contact.leetcode.text": "-> My LeetCode Profile",
  "contact.linkedin.title": "LinkedIn:",
  "contact.linkedin.text": "-> My LinkedIn Profile",
  "contact.itchio.title": "Itch.io:",
  "contact.itchio.text": "-> My Itch.io Profile",
  "contact.youtube.title": "YouTube:",
  "contact.youtube.text": "-> My YouTube Channel",
  "contact.discord.title": "DISCORD:",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Email:",
  "contact.gmail.text": "-> marwen.jlassi@ensi-uma.tn",
  "experiences.expensya.title": "Expensya by Medius",
  "experiences.expensya.position": "Software Engineer | Jul 2024 - Present",
  "experiences.expensya.achievement1": "Worked on the Affidavit Feature 'Missing Receipt Declaration,' which is used by over 5000 users so far, marking a great milestone.",
  "experiences.expensya.achievement2": "Enhanced OCR accuracy by adding new detection features and resolving a significant number of bugs.",
  "experiences.expensya.achievement3": "Developed invoice fraud detection using CNN models.",
  "experiences.value.title": "Value - Digital Services",
  "experiences.value.position": "Full Stack Developer | Internship Jun 2024",
  "experiences.value.achievement1": "Worked on VGreen, a carbon footprint calculator. Transformed the project from a monolithic to a microservices architecture."
};
