export const es = {
  "navbar.button.home": "INICIO",
  "navbar.button.games": "JUEGOS",
  "navbar.button.projects": "PROYECTOS",
  "navbar.button.services": "SERVICIOS",
  "navbar.button.contacts": "CONTACTOS",
  "home.header.title": "¡Hola! Soy MIRO.👋",
  "home.header.subtitle": "Estudiante de Ingeniería Informática & Ingeniero de Software...",
  "home.body.text": "Soy estudiante de Ingeniería Informática en la Escuela Nacional de Informática y un Ingeniero de Software a tiempo parcial en Expensya por Medius. Me encanta usar la tecnología para crear soluciones que marcan la diferencia. El desarrollo de juegos es mi pasatiempo favorito, y disfruto construir experiencias divertidas e inmersivas. ¡Únete a mí en mi viaje donde combino mis habilidades en ingeniería de software y desarrollo de juegos!",
  "cards.button.text": "LEER MÁS ->",
  "services.web.title": "Desarrollo Web",
  "services.web.bodytext": "Puedo ayudarte a crear sitios web responsivos perfectos, rápidos, fáciles de usar y construidos según las mejores prácticas. Con mi experiencia en desarrollo full stack, puedo hacer algo según tus necesidades.",
  "services.game.title": "Desarrollo de Juegos",
  "services.game.bodytext": "Me especializo en la creación de juegos inmersivos y responsivos, fáciles de usar y construidos según las mejores prácticas de la industria. Con mi experiencia en desarrollo de juegos, puedo hacer realidad tu visión y crear algo verdaderamente adaptado a tus necesidades.",
  "services.skills.header": "MIS HABILIDADES",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "MOTORES DE JUEGOS Y HERRAMIENTAS DIVERSAS",
  "contact.header.title": "Contáctame",
  "contact.github.title": "GitHub:",
  "contact.github.text": "-> Mi perfil de GitHub",
  "contact.linkedin.title": "LinkedIn:",
  "contact.linkedin.text": "-> Mi perfil de LinkedIn",
  "contact.itchio.title": "Itch.io:",
  "contact.itchio.text": "-> Mi perfil de Itch.io",
  "contact.youtube.title": "YouTube:",
  "contact.youtube.text": "-> Mi canal de YouTube",
  "contact.discord.title": "DISCORD:",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Correo electrónico:",
  "contact.gmail.text": "-> marwen.jlassi@ensi-uma.tn",
};
