export const es = {
  "navbar.button.home": "INICIO",
  "navbar.button.games": "JUEGOS",
  "navbar.button.projects": "PROYECTOS",
  "navbar.button.services": "SERVICIOS",
  "navbar.button.contacts": "CONTACTOS",
  "home.header.title": "¡Hola! Soy MIRO.👋",
  "home.header.subtitle": "Estudiante de Ingeniería Informática & Ingeniero de Software...",
  "home.body.text": "Soy estudiante de Ingeniería Informática en la Escuela Nacional de Informática y un Ingeniero de Software a tiempo parcial en Expensya por Medius. Me encanta usar la tecnología para crear soluciones que marcan la diferencia. El desarrollo de juegos es mi pasatiempo favorito, y disfruto construir experiencias divertidas e inmersivas. ¡Únete a mí en mi viaje donde combino mis habilidades en ingeniería de software y desarrollo de juegos!",
  "cards.button.text": "LEER MÁS ->",
  "services.fullstack.title": "Desarrollo Full Stack",
  "services.fullstack.bodytext": "Puedo ayudarte a construir aplicaciones full stack robustas, incluyendo desarrollo backend y frontend. Con mi experiencia en desarrollo full stack, puedo crear soluciones adaptadas a tus necesidades.",
  "services.ai.title": "Desarrollo de IA",
  "services.ai.bodytext": "Me especializo en campos de IA como NLP, OCR y Visión por Computadora. Aprovechemos el poder de la IA para construir soluciones innovadoras para tu negocio.",
  "services.game.title": "Desarrollo de Juegos",
  "services.game.bodytext": "Hago desarrollo y diseño de juegos por diversión y freelancing. Creemos experiencias de juego atractivas e inmersivas juntos.",
  "services.skills.header": "MIS HABILIDADES",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "MOTORES DE JUEGOS Y HERRAMIENTAS DIVERSAS",
  "contact.header.title": "Contáctame",
  "contact.github.title": "GitHub:",
  "contact.github.text": "-> Mi perfil de GitHub",
  "contact.leetcode.title": "LeetCode:",
  "contact.leetcode.text": "-> Mi perfil de LeetCode",
  "contact.linkedin.title": "LinkedIn:",
  "contact.linkedin.text": "-> Mi perfil de LinkedIn",
  "contact.itchio.title": "Itch.io:",
  "contact.itchio.text": "-> Mi perfil de Itch.io",
  "contact.youtube.title": "YouTube:",
  "contact.youtube.text": "-> Mi canal de YouTube",
  "contact.discord.title": "DISCORD:",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Correo electrónico:",
  "contact.gmail.text": "-> marwen.jlassi@ensi-uma.tn",
  "experiences.expensya.title": "Expensya por Medius",
  "experiences.expensya.position": "Ingeniero de Software | Jul 2024 - Presente",
  "experiences.expensya.achievement1": "Trabajé en la función de Declaración Jurada 'Declaración de Recibo Faltante', que es utilizada por más de 5000 usuarios hasta ahora, marcando un gran hito.",
  "experiences.expensya.achievement2": "Mejoré la precisión del OCR agregando nuevas características de detección y resolviendo un número significativo de errores.",
  "experiences.expensya.achievement3": "Desarrollé la detección de fraudes en facturas utilizando modelos CNN.",
  "experiences.value.title": "Value - Servicios Digitales",
  "experiences.value.position": "Desarrollador Full Stack | Pasantía Jun 2024",
  "experiences.value.achievement1": "Trabajé en VGreen, una calculadora de huella de carbono. Transformé el proyecto de una arquitectura monolítica a una de microservicios."
};
