export const fr = {
  "navbar.button.home": "ACCUEIL",
  "navbar.button.games": "JEUX",
  "navbar.button.projects": "PROJETS",
  "navbar.button.services": "SERVICES",
  "navbar.button.contacts": "CONTACTS",
  "home.header.title": "Hola! Je suis MIRO.👋",
  "home.header.subtitle": "Étudiant en Ingénierie Informatique & Ingénieur Logiciel...",
  "home.body.text": "Je suis étudiant en Ingénierie Informatique à l'École Nationale d'Informatique et ingénieur logiciel à temps partiel chez Expensya par Medius. J'adore utiliser la technologie pour créer des solutions qui font la différence. Le développement de jeux est mon passe-temps favori, et j'aime construire des expériences amusantes et immersives. Rejoignez-moi dans mon parcours où je combine mes compétences en ingénierie logicielle et en développement de jeux !",
  "cards.button.text": "EN SAVOIR PLUS ->",
  "services.fullstack.title": "Développement Full Stack",
  "services.fullstack.bodytext": "Je peux vous aider à construire des applications full stack robustes, incluant le développement backend et frontend. Avec mon expertise en développement full stack, je peux créer des solutions adaptées à vos besoins.",
  "services.ai.title": "Développement IA",
  "services.ai.bodytext": "Je me spécialise dans les domaines de l'IA tels que le NLP, l'OCR et la Vision par Ordinateur. Tirons parti de la puissance de l'IA pour construire des solutions innovantes pour votre entreprise.",
  "services.game.title": "Développement de Jeux",
  "services.game.bodytext": "Je fais du développement et de la conception de jeux pour le plaisir et en freelance. Créons ensemble des expériences de jeu engageantes et immersives.",
  "services.skills.header": "MES COMPÉTENCES",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "MOTEURS DE JEU ET OUTILS DIVERS",
  "contact.header.title": "Contactez-moi",
  "contact.github.title": "GitHub :",
  "contact.github.text": "-> Mon profil GitHub",
  "contact.leetcode.title": "LeetCode :",
  "contact.leetcode.text": "-> Mon profil LeetCode",
  "contact.linkedin.title": "LinkedIn :",
  "contact.linkedin.text": "-> Mon profil LinkedIn",
  "contact.itchio.title": "Itch.io :",
  "contact.itchio.text": "-> Mon profil Itch.io",
  "contact.youtube.title": "YouTube :",
  "contact.youtube.text": "-> Ma chaîne YouTube",
  "contact.discord.title": "DISCORD :",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Email :",
  "contact.gmail.text": "-> marwen.jlassi@ensi-uma.tn",
  "experiences.expensya.title": "Expensya par Medius",
  "experiences.expensya.position": "Ingénieur Logiciel | Juil 2024 - Présent",
  "experiences.expensya.achievement1": "J'ai travaillé sur la fonctionnalité de Déclaration sous serment 'Déclaration de reçu manquant', utilisée par plus de 5000 utilisateurs à ce jour, marquant une grande étape.",
  "experiences.expensya.achievement2": "J'ai amélioré la précision de l'OCR en ajoutant de nouvelles fonctionnalités de détection et en résolvant un nombre significatif de bugs.",
  "experiences.expensya.achievement3": "J'ai développé la détection de fraude des factures en utilisant des modèles CNN.",
  "experiences.value.title": "Value - Services Numériques",
  "experiences.value.position": "Développeur Full Stack | Stage Juin 2024",
  "experiences.value.achievement1": "J'ai travaillé sur VGreen, un calculateur d'empreinte carbone. J'ai transformé le projet d'une architecture monolithique à une architecture de microservices."
};
