export const en = {
  "navbar.button.home": "HOME",
  "navbar.button.games": "GAMES",
  "navbar.button.projects": "PROJECTS",
  "navbar.button.services": "SERVICES",
  "navbar.button.contacts": "CONTACTS",
  "home.header.title": "Hola! I'm MIRO.👋",
  "home.header.subtitle": "Computer Science Engineering Student & Software Engineer...",
  "home.body.text": "I’m a Computer Science Engineering student at the National School of Computer Science and a part-time Software Engineer at Expensya by Medius. I love using technology to create solutions that make a difference.Game development is my favorite hobby, and I enjoy building fun and immersive experiences. Join me on my journey as I combine my skills in software engineering and game development!",
  // "home.body.text": "I’m a Computer Science Engineering student at the <strong style=\"color: #41abfd\">National School of Computer Science</strong> and a part-time Software Engineer at <strong style=\"color: #41abfd\">Expensya</strong> by Medius.<br /> I love using technology to create solutions that make a difference. Game development is my favorite hobby, and I enjoy building fun and immersive experiences.<br /> Join me on my journey as I combine my skills in software engineering and game development!",
  "cards.button.text": "READ MORE ->",
  "services.web.title": "Web Development",
  "services.web.bodytext": "I can help you create the perfect responsive websites that are fast, easy to use, and built with best practices. With my expertise in full stack development, I can make something according to your needs.",
  "services.game.title": "Game Development",
  "services.game.bodytext": "I specialize in crafting immersive and responsive games, user-friendly, and built with industry best practices. With my expertise in game development, I can bring your vision to life and create something truly tailored to your needs.",
  "services.skills.header": "MY SKILLS",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "GAME ENGINES AND DIVERSE TOOLS",
  "contact.header.title": "Contact Me",
  "contact.github.title": "GitHub:",
  "contact.github.text": "-> My GitHub Profile",
  "contact.linkedin.title": "LinkedIn:",
  "contact.linkedin.text": "-> My LinkedIn Profile",
  "contact.itchio.title": "Itch.io:",
  "contact.itchio.text": "-> My Itch.io Profile",
  "contact.youtube.title": "YouTube:",
  "contact.youtube.text": "-> My YouTube Channel",
  "contact.discord.title": "DISCORD:",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Email:",
  "contact.gmail.text": "-> marwen.jlassi@ensi-uma.tn",
};
