export const fr = {
  "navbar.button.home": "ACCUEIL",
  "navbar.button.games": "JEUX",
  "navbar.button.projects": "PROJETS",
  "navbar.button.services": "SERVICES",
  "navbar.button.contacts": "CONTACTS",
  "home.header.title": "Hola! Je suis MIRO.👋",
  "home.header.subtitle": "Étudiant en Ingénierie Informatique & Ingénieur Logiciel...",
  "home.body.text": "Je suis étudiant en Ingénierie Informatique à l'École Nationale d'Informatique et ingénieur logiciel à temps partiel chez Expensya par Medius. J'adore utiliser la technologie pour créer des solutions qui font la différence. Le développement de jeux est mon passe-temps favori, et j'aime construire des expériences amusantes et immersives. Rejoignez-moi dans mon parcours où je combine mes compétences en ingénierie logicielle et en développement de jeux !",
  "cards.button.text": "EN SAVOIR PLUS ->",
  "services.web.title": "Développement Web",
  "services.web.bodytext": "Je peux vous aider à créer des sites web réactifs parfaits, rapides, faciles à utiliser et conçus selon les meilleures pratiques. Avec mon expertise en développement full stack, je peux répondre à vos besoins.",
  "services.game.title": "Développement de Jeux",
  "services.game.bodytext": "Je suis spécialisé dans la création de jeux immersifs et réactifs, conviviaux et construits selon les meilleures pratiques de l'industrie. Grâce à mon expertise en développement de jeux, je peux concrétiser votre vision et créer quelque chose véritablement adapté à vos besoins.",
  "services.skills.header": "MES COMPÉTENCES",
  "services.skills.mean": "FULL STACK- MEAN",
  "services.skills.game_engines": "MOTEURS DE JEU ET OUTILS DIVERS",
  "contact.header.title": "Contactez-moi",
  "contact.github.title": "GitHub :",
  "contact.github.text": "-> Mon profil GitHub",
  "contact.linkedin.title": "LinkedIn :",
  "contact.linkedin.text": "-> Mon profil LinkedIn",
  "contact.itchio.title": "Itch.io :",
  "contact.itchio.text": "-> Mon profil Itch.io",
  "contact.youtube.title": "YouTube :",
  "contact.youtube.text": "-> Ma chaîne YouTube",
  "contact.discord.title": "DISCORD :",
  "contact.discord.text": "-> miro#3878",
  "contact.gmail.title": "Email :",
  "contact.gmail.text": "-> marwen.jlassi&#64;ensi-uma.tn",
};
